name: Fetch Ameren Rates

on:
  schedule:
    # Runs at 7 PM Central Time (1 AM UTC next day during CST, 12 AM UTC during CDT)
    # Using 1 AM UTC to cover CST (most of the year)
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-rates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz aiohttp
    
    - name: Run fetcher
      run: |
        python ameren_fetcher.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ameren_rates.json
        git diff --staged --quiet || git commit -m "Update Ameren rates - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
